---
title: "Midterm"
author: "Connor Bailey"
date: "11/5/23"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: cerulean
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
projPath <- dirname(rstudioapi::documentPath())
setwd(projPath)
```
```{r libraries, include=FALSE}

library(fpp3)
library(plotly)
library(car)
library(forecast)
library(ggthemes)
library(tibbletime)
theme_set(theme_solarized())
```

# Import  Data
```{block data, type = 'written_answer'}

I chose CO2 emissions from the transportation sector in the US, from 1973 to 2023. I obtained this data from the US Energy Information Administration. We will be examining 1973-2012 and observing how our forecasting models compare with the effects of the 2008 recession. The recession negatively impact many sectors of the economy, including transportation. Therefore, a drop-off in CO2 emissions in 2008 is expected. We will import the data, filter and organzie it, and convert it into a time-series.

```
```{r}

# Importing data f
df.gas <- read.csv("Data/natural_gas.csv")

# Cleaning and organizing consumption data frame
df.gas <- df.gas |> 
  filter(Description == "Natural Gas Consumption",
         substr(YYYYMM, 5, 6) != 13,
         between(substr(YYYYMM, 1, 4), "2017", "2022")) |>
  mutate(Year = substr(YYYYMM, 1, 4),
         Month = substr(YYYYMM, 5, 6),
         YearMonth = yearmonth(paste(Year, Month)),
         Consumption = as.numeric(Value)) |>
  select(YearMonth, Consumption) 

# Generating a time-series
myts <- df.gas |>
  as_tsibble(index = YearMonth, key = c(Consumption)) |>
  arrange(YearMonth)

```

# Time-Series Plot
```{block plot1, type = 'written_answer'}
Now that we have our time-series the first step is to visualize the series.
```
```{r}

# Plotting the time-series
ggplot(myts, aes(x = YearMonth, y = Consumption)) + 
  geom_point(aes(y = Consumption)) + 
  geom_line(aes(y = Consumption)) +
  labs(title = "Time-Series of Natural Gas Consumption",
       subtitle = "in USA (2017-2022)",
       x = "Month",
       y = "Billion Cubic Feet") 

```

# Train & Test Sets
```{block train_test, type = 'written_answer'}
In order to assess the accuracy of our ETS models, we will need to split our data in to 'train' and 'test' data sets. The first 80% of the data, 1973-2005, will be put in the train set, and the final 20%, 2006-2012, will be put in the test data set. 
```
```{r}

train <- as_tsibble(myts[1:60,], index = YearMonth, key = c(Consumption))
test <- as_tsibble(myts[61:72,], index = YearMonth, key = c(Consumption))

```

# Box-Cox Transformation 
```{block box-cox, type = 'written_answer'}
In the time-series plot we could see that the seasonality was not uniform. To improve this, we will implement the Box-Cox transformation. Specifically we will utilize the guerrero method to determine the optimal lambda value, and then use that lambda value to transform the data accordingly.  
```
```{r}

lambda <- BoxCox.lambda(train$Consumption, method = c("guerrero"))

train$Consumption <- train$Consumption^lambda
train <- as_tsibble(train, index = YearMonth)
test$Consumption <- test$Consumption^lambda
test <- as_tsibble(test, index = YearMonth)

```

# Model Generation
```{block models1, type = 'written_answer'}
Now we will create a few ETS forecasting models using the training data set. The first model will be the automatically optimized ETS model. For the other two, we will manually enter specifications for the seasonal, trend, and error components.
```
```{r}

fit <- train |> model(
  SNAIVE = SNAIVE(Consumption),
  ETS = ETS(Consumption),
  ARIMA = ARIMA(Consumption))

```
```{block models2, type = 'written_answer'}
As we can see, the optimized ETS model has multiplicative seasonality, an additive damped trend, and multiplicative error. The second ETS model is completely different, with all seasonality and error being additive, and the trend component removed. The final model has no seasonal component and the trend and error are multiplicative. Let's forecast with these models and see how they perform.
```

# Residual Analysis
```{block resid1, type = 'written_answer'}
Before we can forecast, we need to analyze the residuals of our models. 
```
```{r}

# Residuals Plot
augment(fit) |>
  autoplot(.resid) +
  labs(title = "Residuals for All Models",
       y = "Residuals")

# ACF Plots
augment(fit) |>
  ACF(.resid) |>
  autoplot() +
  labs(title = "ACF for All Models",
       y = "ACF")

# Portmanteau Test (Ljung-Box Test)
augment(fit) |>
  features(.resid, ljung_box, lag = 24)

```
```{block resid2, type = 'written_answer'}
Considering the residual plots first, we see that the residuals of three of the four models have uniform variance around zero. The residuals of the seasonal naive model are weighted on the positive side and grow in magnitude with time. For all four models, there are no large outliers and the majority of the residuals are between one and negative one. 

If we consider the ACF plots, we see apparent autocorrelation in the naive and drift models, and slight autocorrelation in the seasonal naive model. The ETS model, however, appears uncorrelated, with a mean of zero, and constant variance. This is a positive sign for this particular forecasting model. 
```
# Forecast
```{r}

# Plotting all models seperatly
fit |> select(c(ETS)) |> forecast(h = 12) |> autoplot(train) +
  autolayer(test) +
  labs(title = "ETS Model Forecast",
       x = "Month",
       y = "Transformed Natural Gas Consumption") 
fit |> select(c(ARIMA)) |> forecast(h = 12) |> autoplot(train) +
  autolayer(test) +
  labs(title = "ARIMA Model Forecast",
       x = "Month",
       y = "Transformed Natural Gas Consumption") 
fit |> select(c(SNAIVE)) |> forecast(h = 12) |> autoplot(train) +
  autolayer(test) +
  labs(title = "Seasonal Naive Model Forecast",
       x = "Month",
       y = "Transformed Natural Gas Consumption") 

```
```{block forecast, type = 'written_answer'}
The data we have chosen to analyze and forecast with is particularly challenging because the 2008 recession was unforseen, at least within this data set. The optimized ETS model performs the best among the three generated. The point forecast is higher than the actual emissions data, as expected. However, the actual values do lie within the prediction intervals. This is not the case for either our second or third ETS models. The second model has no trend component and is not terrible, as the data trend before the recession was upward. However, because the error component is additive, the prediction intervals are tight and do not contain the actual values. Lastly, the third model, which has no seasonal component and multiplicative trend and error, is way off. As previously said, the data trend was upward, so the forecast increases. However, the wide prediction intervals do not contain the actual values even with multiplicative error. 
```

# Accuracy
```{block accuracy1, type = 'written_answer'}
To assess the accuracy of our forecast models more specifically, we need to compare the generated forecasts against the test data with the following metrics:
```
### Point Forecast Accuracy
``` {r}

myf <- fit |> forecast(h = 12)

accuracy(myf, test) |>
  mutate(Model = .model) |>
  select(c(Model, MAE, RMSE, MAPE)) |>
  arrange(MAPE)

```
```{block accuracy2, type = 'written_answer'}
Oddly enough, the forecast generated with the ETS2 model (no trend) outperformed the other two, in terms of point forecast accuracy. If we consider the mean absolute percentage error (MAPE), our ETS2 forecast is only ~12% different than the actual values from the test set, and the ETS1 was ~14% different. These are not a great figures, but as we mentioned, this dataset is uniquely challenging to forecast, given the recession. 
```
### Prediction Interval Accuracy
```{block accuracy3, type = 'written_answer'}
Next, we need to analyze the accuracy of the prediction intervals of our forecast models. To do this we will examine the continuous ranked probability score (CRPS):
```
``` {r}

myf |> accuracy(test, list(crps =CRPS)) |>
  mutate(Model = .model,
         CRPS = crps) |>
  select(c(Model, CRPS)) |>
  arrange(CRPS)

```
```{block accuracy4, type = 'written_answer'}
Again the ETS2 model outperformed the other two. This is initially surprising. However, given that the trend of the data prior to the 2008 recession was upward, it makes intuitive sense that the model lacking any trend component would outperform the others. 
```